import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";

/**
 * Bundles the serverless handler into a single self-contained ESM file.
 *
 * Vercel's Node builder does not transpile or dependency-trace a handler that
 * imports npm-workspace packages by name: it ships the raw source and the
 * runtime then fails to resolve anything. Bundling here removes that
 * dependency on the platform's tracing entirely, and the emitted file is a
 * plain .mjs the runtime can load directly.
 */
mkdirSync("api", { recursive: true });

await build({
  entryPoints: ["serverless/handler.mts"],
  outfile: "api/index.mjs",
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  // better-sqlite3 is a native module and is not used by the serverless
  // handler, which runs the in-memory ledger instead. Marking it external
  // keeps esbuild from trying to bundle a .node binary.
  external: ["better-sqlite3"],
  banner: {
    // Some transitive dependencies are CommonJS and call require() at load
    // time (node-fetch, reached through the Razorpay SDK). Bundling those into
    // an ESM output leaves require undefined, so it is recreated here.
    js: [
      "// Generated by scripts/build-api.mjs. Edit serverless/handler.mts instead.",
      "import { createRequire as __createRequire } from 'node:module';",
      "import { fileURLToPath as __fileURLToPath } from 'node:url';",
      "import { dirname as __dirname_ } from 'node:path';",
      "const require = __createRequire(import.meta.url);",
      "const __filename = __fileURLToPath(import.meta.url);",
      "const __dirname = __dirname_(__filename);",
    ].join("\n"),
  },
  logLevel: "info",
});

// The bundle is ESM; this makes that explicit to the runtime regardless of
// what the enclosing package.json says.
writeFileSync("api/package.json", `${JSON.stringify({ type: "module" }, null, 2)}\n`);

console.log("Bundled serverless handler to api/index.mjs");
